import Head from 'next/head'
import { WrapperPage } from '../src/wrappers/pages'
import { ContactUsPage } from '../src/containers/contact-us'
import { withPublickRoute } from "../src/middleware/publickRouter";

const ContactUs = () => {
    return (
        <>
            <Head>
                <title>Contact us</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <WrapperPage>
                <ContactUsPage />
            </WrapperPage >
        </>
    )
}

export const getServerSideProps = withPublickRoute();

export default ContactUs;
