import Head from 'next/head'
import { WrapperPage } from '../src/wrappers/pages'
import { ContactUsPage } from '../src/containers/contact-us'

export default function ContactUs() {
    return (
        <>
            <Head>
                <title>Contact us</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <WrapperPage>
                <ContactUsPage />
            </WrapperPage >
        </>
    )
}
