import Head from 'next/head'
import { WrapperPage } from '../src/wrappers/pages'
import { FaqsPage } from '../src/containers/faqs-page'

export default function Faqs() {
    return (
        <>
            <Head>
                <title>Faqs page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <WrapperPage>
                <FaqsPage />
            </WrapperPage >
        </>
    )
}
