import Head from 'next/head'
import { WrapperPage } from '../src/wrappers/pages'
import { FaqsPage } from '../src/containers/faqs-page'
import { withPublickRoute } from "../src/middleware/publickRouter";

const Faqs = () => {
    return (
        <>
            <Head>
                <title>Faqs page</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <WrapperPage>
                <FaqsPage />
            </WrapperPage >
        </>
    )
}

export const getServerSideProps = withPublickRoute();

export default Faqs;