import Head from 'next/head'
import { WrapperPage } from '../src/wrappers/pages'
import { HomePage } from '../src/containers/home-page'
import { withPublickRoute } from "../src/middleware/publickRouter";

const Home = () => {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <WrapperPage>
        <HomePage />
      </WrapperPage >
    </>
  )
}

export const getServerSideProps = withPublickRoute();

export default Home;